### ISSUE TITLE
`npx rowscript` error

### ISSUE THREAD

**Issue by CziSKY** [rowscript/rowscript#84]
I'm starting my RowScript journey by following the 'Getting Started' section of the website. When I try to compile `.rows` file into  `.mjs` file, the following issue occurs:

```shell
npx rowscript

/Users/***/Desktop/WorkSpace/RowScript/Test/node_modules/rowscript/cli/npm/index.js:16
        throw new Error(`Binary not found in node_modules (${os}-${arch})`);
        ^

Error: Binary not found in node_modules (darwin-arm64)
    at binPath (/Users/***/Desktop/WorkSpace/RowScript/Test/node_modules/rowscript/cli/npm/index.js:16:15)
    at Object.<anonymous> (/Users/***/Desktop/WorkSpace/RowScript/Test/node_modules/rowscript/cli/npm/index.js:20:24)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.15.0
```

Operating system is MacOS 13.3.1.

**Comment by anqurvanillapy** [comment]
Ah yes, it's because I didn't release the Darwin ARM64 version of the compiler, you could try cloning the repo and running some tests in `core/src/tests` for now. A new Action step to release the ARM64 binaries should be added, which's definitely a low-hanging fruit.

**Comment by anqurvanillapy** [comment]
@CziSKY You could temporarily make the `release.yml` run on `on.pull_request` for your PR to test the releases, and rollback to `on.tags` after everything looks good. I will publish a new version `v1.0.0-alpha.4` for you.
